// Centralized ionicons exports for Naive UI icon usage across the app.
export {
  ArrowUndoCircleOutline,
  BedOutline,
  CalendarOutline,
  CardOutline,
  CartOutline,
  CheckmarkCircle,
  CheckmarkCircleOutline,
  CloudUploadOutline,
  CloseCircle,
  CloseCircleOutline,
  ColorPaletteOutline,
  DocumentAttachOutline,
  DocumentTextOutline,
  EyeOutline,
  HammerOutline,
  Heart,
  HeartOutline,
  HomeOutline,
  LayersOutline,
  LockClosedOutline,
  PersonCircleOutline,
  PhonePortraitOutline,
  PricetagOutline,
  RefreshOutline,
  SearchOutline,
  ShieldCheckmarkOutline,
  Time,
} from '@vicons/ionicons5'

// Recommended business aliases for new pages/components.
export {
  AddOutline as IconAdd,
  ArrowBackOutline as IconBack,
  CloudUploadOutline as IconUpload,
  CreateOutline as IconEdit,
  DownloadOutline as IconDownload,
  EyeOutline as IconView,
  RefreshOutline as IconRefresh,
  SaveOutline as IconSave,
  SearchOutline as IconSearch,
  TrashOutline as IconDelete,
} from '@vicons/ionicons5'
